language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4.0"

services:
  - redis-server

before_install:
  - test $TRAVIS_NODE_VERSION = '0.8' && npm install -g npm@1.2.8000 || true

before_script:
  - make travis-run

env: TRAVIS=1

sudo: false
